### ISSUE TITLE
SpongeForge-RC3928及之后出现的工作台刷物品bug

### ISSUE THREAD

**Issue by sudaku** [euOnmyoji/EpicBanItem---Sponge#16]
Forge版本: forge-1.12.2-14.23.5.2838
SpongeForge版本: spongeforge-1.12.2-2838-7.1.7-RC3944.jar
安装的mod: industrialcraft-2-2.8.187-ex112.jar
安装的插件: EpicBanItem-0.3.2-b268.jar
复现操作: 举个例子, 现在有10个mox棒和64个铁板, 本来应该合成5个双联mox棒，但是当你按住shift后, 将直接消耗掉所有的铁板并产生64个双联mox棒.
复现视频
[record.zip](https://github.com/euOnmyoji/EpicBanItem---Sponge/files/3792351/record.zip)

**Comment by ustc-zzzz** [comment]
请确认是否有安装 Crafting Recipe Redirector

**Comment by sudaku** [comment]
> 请确认是否有安装 Crafting Recipe Redirector

没有，单独测试只安装了一个工业mod和这个ebi

**Comment by ginyai** [comment]
https://github.com/SpongePowered/SpongeCommon/pull/2414

**Comment by cybmp3** [comment]
> 
> 
> [SpongePowered/SpongeCommon#2414](https://github.com/SpongePowered/SpongeCommon/pull/2414)

老哥老哥，能不能帮帮把这个问题也看看呀https://github.com/SpongePowered/SpongeForge/issues/3021
也是类似刷刷刷的bug

**Comment by ginyai** [comment]
@cybmp3 更新到sponge forge 1.12.2-2838-7.1.7 或之后的版本应该就可以了
