### ISSUE TITLE
/ebi create and /ebi query differ

### ISSUE THREAD

**Issue by clienthax** [euOnmyoji/EpicBanItem---Sponge#17]
/ebi create on a item with damage value does not place the damage value into the config.

![image](https://user-images.githubusercontent.com/1056270/69544355-710e8500-0f87-11ea-96ed-999f7669f3eb.png)

```
epicbanitem {
    "opencomputers:component"=[
        {
            name=ban-creative-apu
            priority=5
            query {
                id="opencomputers:component"
            }
            update {
                "$set" {
                    Damage=0
                    id="minecraft:air"
                }
            }
        }
    ]
}
epicbanitem-version=1

```

**Comment by ustc-zzzz** [comment]
It's intended. Try adding `--simple-capture` flag.

* `/ebi create` captures only item types
* `/ebi create --simple-capture` captures item types and damge values
* `/ebi create --all-capture` captures everything including item types, damage values, and the nbt tag
