### ISSUE TITLE
Reduce log file size

### ISSUE THREAD

**Issue by phit** [euOnmyoji/EpicBanItem---Sponge#6]
https://github.com/euOnmyoji/EpicBanItem---Sponge/blob/76a03c09822cd3fb9b00ba88c498eb1e160d62fb/src/main/java/com/github/euonmyoji/epicbanitem/configuration/BanConfig.java#L51

creates insanely large debug.log logs for modded servers, like up to 200000 lines long
would be nice if you could throw this behind a config setting that disables this output by default

thanks!

**Comment by ustc-zzzz** [comment]
Fixed in v0.2.2 by adding a config option.
