### ISSUE TITLE
Left Click not being checked when hitting mob.

### ISSUE THREAD

**Issue by AzureZhen** [euOnmyoji/EpicBanItem---Sponge#7]
Version: 0.2.3
Issue: Plugin is currently not checking the use trigger when hitting a mob (in my case all my mobs are customnpcs) with left click, therefore allowing swords and such to be used when "banned". Bows and other items that are used via right-clicked are being blocked just fine that way but the left click is not being checked at all. 

Here is how my ban is set up in the banitem.conf
```
"mmorpg:sword/sword0"=[
        {
            name=common-sword
            priority=5
            query {
                id="mmorpg:sword/sword0"
            }
            use-trigger {
                click=false
                drop=true
                interact=true
                throw=true
                use=true
            }
        }
    ]
```
My permissions plugin is LuckPerms version: 4.3.80 (The latest at this time)

**Comment by ginyai** [comment]
I tried it myself, the use trigger works fine with "minecraft:diamond_sword" & customnpcs.

**Comment by AzureZhen** [comment]
I figured out the mod that is causing the issue! https://minecraft.curseforge.com/projects/better-combat-rebirth when I have this mod installed, it seems to change something that breaks your permission checks.

**Comment by AzureZhen** [comment]
Was wonder if there any plans to fix this incompatibility or am I better off looking for a different dual wielding mod?

**Comment by ginyai** [comment]
I think it's better to modify at the mod side.
https://github.com/ginyai/BetterCombatRebirth
