### ISSUE TITLE
Unable to find command

### ISSUE THREAD

**Issue by TowardtheStars** [euOnmyoji/EpicBanItem---Sponge#9]
[log](https://paste.ubuntu.com/p/KG5Mv85DyT/)

**Comment by ginyai** [comment]
I try with the same version of forge & sponge, and the command works fine.
Can you provide more information like full debug log.

**Comment by TowardtheStars** [comment]
Emm... I accidentally mistook the version of spongeforge used, which was prior to the version you marked on wiki. Sorry!
